package org.zstack.zmigrate;

public enum ZMigratePluginErrors {
    GENERIC_ERROR(1000),

    // in ZMigrate client: 2xxx
    ZMIGRATE_CREATE_ACCOUNT_ERROR(2001),
    ZMIGRATE_VERIFY_PLATFORM_CONNECTION_ERROR(2002),
    ZMIGRATE_REGISTER_ZSV_TO_ZMIGRATE_ERROR(2003),
    ZMIGRATE_VERIFY_GATEWAY_CONNECTION_ERROR(2004),
    ZMIGRATE_REGISTER_GATEWAY_TO_ZMIGRATE_ERROR(2005),
    ZMIGRATE_GET_ZMIGRATE_MANAGEMENT_SERVER_INFO_ERROR(2006),
    ZMIGRATE_GET_PLATFORM_INFOS_ERROR(2007),
    ZMIGRATE_GET_GATEWAY_SERVER_INFOS_ERROR(2008),
    ZMIGRATE_GET_MIGRATE_JOBS_ERROR(2009),
    ZMIGRATE_ENCRYPT_KEY_ERROR(2011),
    ZMIGRATE_GATEWAY_ERROR(2012),
    ZMIGRATE_EXPORT_ACTIVATION_INFOS_ERROR(2013),
    ZMIGRATE_IMPORT_ACTIVATION_PACKAGE_ERROR(2014),

    // ZMIGRATE_VM_STATE error: 3xxx
    UNEXPECTED_ZMIGRATE_VM_STATE(3000),
    MISSING_ZMIGRATE_VM(3001),

    // INVALID_CONFIG error: 4xxx
    INVALID_CONFIG(4000),
    INVALID_ZMIGRATE_TAGS(4001),
    ;

    private String code;

    ZMigratePluginErrors(int id) {
        code = String.format("ZMigrate.%s", id);
    }

    @Override
    public String toString() {
        return code;
    }
}
