package org.zstack.zwatch.alarm.system;

public interface SystemAlarmManager {

    String DATA_DIR_CAPACITY_ALARM_NAME_CN = "系统数据目录磁盘容量报警器";
    String DATA_DIR_CAPACITY_ALARM_NAME = "System Data Directory Disk Capacity";
    String DATA_DIR_CAPACITY_ALARM_UUID = "b632652cc16044cdb6b4f516ed93a118";

    String HOST_ROOT_USED_CAPACITY_ALARM_NAME_CN = "主机根盘使用率报警器";
    String HOST_ROOT_USED_CAPACITY_ALARM_NAME = "Host Root Volume Utilization";
    String HOST_ROOT_USED_CAPACITY_ALARM_UUID = "5d3bb9d271a349b283893317f531f723";

    String BACKUP_STORAGE_AVAILABLE_CAPACITY_ALARM_NAME_CN = "镜像存储可用容量报警器";
    String BACKUP_STORAGE_AVAILABLE_CAPACITY_ALARM_NAME = "Image Storage Available Capacity";
    String BACKUP_STORAGE_AVAILABLE_CAPACITY_ALARM_UUID = "44e6f054a59a451fb1b535accff64fc2";

    String PRIMARY_STORAGE_AVAILABLE_CAPACITY_ALARM_NAME_CN = "数据存储可分配容量报警器";
    String PRIMARY_STORAGE_AVAILABLE_CAPACITY_ALARM_NAME = "Data Storage Allocatable Capacity";
    String PRIMARY_STORAGE_AVAILABLE_CAPACITY_ALARM_UUID = "66dfdee6fd314aac96ca3779774ad977";

    String PRIMARY_STORAGE_PHYSICAL_AVAILABLE_CAPACITY_ALARM_NAME_CN = "数据存储可用物理容量报警器";
    String PRIMARY_STORAGE_PHYSICAL_AVAILABLE_CAPACITY_ALARM_NAME = "Data Storage Available Physical Capacity";
    String PRIMARY_STORAGE_PHYSICAL_AVAILABLE_CAPACITY_ALARM_UUID = "ded02f9786444c6296e9bc3efb8eb484";

    String BACKUP_STORAGE_DISCONNECT_EVENT_ALARM_NAME_CN = "镜像存储未连接";
    String BACKUP_STORAGE_DISCONNECT_EVENT_ALARM_NAME = "Backup Storage Disconnected";
    String BACKUP_STORAGE_DISCONNECT_EVENT_ALARM_UUID = "98f9c802604e4852bd84716f66cf4f73";

    String BACKUP_STORAGE_CONNECTED_EVENT_ALARM_NAME_CN = "镜像存储已连接";
    String BACKUP_STORAGE_CONNECTED_EVENT_ALARM_NAME = "Backup Storage Connected";
    String BACKUP_STORAGE_CONNECTED_EVENT_ALARM_UUID = "55365763fed244c39b4642bef6c5daf9";

    String PRIMARY_STORAGE_DISCONNECT_EVENT_ALARM_NAME_CN = "数据存储未连接";
    String PRIMARY_STORAGE_DISCONNECT_EVENT_ALARM_NAME = "Primary Storage Disconnected";
    String PRIMARY_STORAGE_DISCONNECT_EVENT_ALARM_UUID = "5e75230bd2ea4f47abf6ff92fa816a20";

    String PRIMARY_STORAGE_CONNECTED_EVENT_ALARM_NAME_CN = "数据存储已连接";
    String PRIMARY_STORAGE_CONNECTED_EVENT_ALARM_NAME = "Primary Storage Connected";
    String PRIMARY_STORAGE_CONNECTED_EVENT_ALARM_UUID = "f56795b8c34b452f84bcf25cb89bded2";

    String MANAGEMENT_NODE_LEFT_EVENT_ALARM_NAME_CN = "管理节点未连接";
    String MANAGEMENT_NODE_LEFT_EVENT_ALARM_NAME = "Management Node Disconnected";
    String MANAGEMENT_NODE_LEFT_EVENT_ALARM_UUID = "8eca1096feb34419913087d2b281ecec";

    String MANAGEMENT_NODE_JOIN_EVENT_ALARM_NAME_CN = "管理节点已连接";
    String MANAGEMENT_NODE_JOIN_EVENT_ALARM_NAME = "Management Node Connected";
    String MANAGEMENT_NODE_JOIN_EVENT_ALARM_UUID = "10d9c4e69fc2456bb8c6c6d456bb5038";

    String MANAGEMENT_NODE_DB_FENCER_IP_UNREACHABLE_ALARM_NAME_CN = "仲裁IP不可达报警器";
    String MANAGEMENT_NODE_DB_FENCER_IP_UNREACHABLE_ALARM_NAME = "Monitor IP Unreachable";
    String MANAGEMENT_NODE_DB_FENCER_IP_UNREACHABLE_ALARM_UUID = "065f9609dce141bb952c80f729f58af4";

    String MANAGEMENT_NODE_DB_SYNCHRONIZATION_ALARM_NAME_CN = "双管理节点数据库不同步报警器";
    String MANAGEMENT_NODE_DB_SYNCHRONIZATION_ALARM_NAME = "Dual Management Node Database Needs Synchronization";
    String MANAGEMENT_NODE_DB_SYNCHRONIZATION_ALARM_UUID = "712c3dec6aa94ed2b3bcd32192c22f69";

    String HOST_DISCONNECT_ALARM_NAME_CN = "主机未连接";
    String HOST_DISCONNECT_ALARM_NAME = "Host Disconnected";
    String HOST_DISCONNECT_ALARM_UUID = "4a3cb114b10d41e19545ab693222c134";

    String HOST_HARDWARE_CHANGED_ALARM_NAME_CN = "主机硬件发生变化";
    String HOST_HARDWARE_CHANGED_ALARM_NAME = "Host Hardware Changed";
    String HOST_HARDWARE_CHANGED_ALARM_UUID = "829d96de006043c3b34202861ca82078";

    String HOST_CONNECTED_ALARM_NAME_CN = "主机已连接";
    String HOST_CONNECTED_ALARM_NAME = "Host Connected";
    String HOST_CONNECTED_ALARM_UUID = "1a7a3eb433904df89f5c42a1fa4e0716";

    String VM_CRASH_EVENT_ALARM_NAME_CN = "虚拟机故障";
    String VM_CRASH_EVENT_ALARM_NAME = "VM Crashed";
    String VM_CRASH_EVENT_ALARM_UUID = "a391bb01fd954ed3b6c0569ecc7b5764";

    String SECURITY_MACHINE_STATE_CHANGE_EVENT_ALARM_NAME_CN = "密码机异常通知";
    String SECURITY_MACHINE_STATE_CHANGE_EVENT_ALARM_NAME = "HSM Exception Notification";
    // uuid has changed since ZSphere 4.10.3. original: "d3ba391bb01fd954eecc7b576c056964"
    String SECURITY_MACHINE_STATE_CHANGE_EVENT_ALARM_UUID = "00da391bb01f29549ecc7b576c056911";

    String SECRET_RESOURCE_POOL_STATUS_CHANGE_EVENT_ALARM_NAME_CN = "第三方密码服务异常";
    String SECRET_RESOURCE_POOL_STATUS_CHANGE_EVENT_ALARM_NAME = "3rd-Party Cryptographic Service Error";
    String SECRET_RESOURCE_POOL_STATUS_CHANGE_EVENT_ALARM_UUID = "eecc7b576c05391bb01fd956964d3ba4";

    String HOST_PHYSICAL_NIC_STATUS_UP_EVENT_ALARM_NAME_CN = "主机网卡已连接";
    String HOST_PHYSICAL_NIC_STATUS_UP_EVENT_ALARM_NAME = "Host NIC Connected";
    String HOST_PHYSICAL_NIC_STATUS_UP_EVENT_ALARM_UUID = "d1d122f95c194c958ba1be4a3568ebd0";

    String HOST_PHYSICAL_NIC_STATUS_DOWN_EVENT_ALARM_NAME_CN = "主机网卡未连接";
    String HOST_PHYSICAL_NIC_STATUS_DOWN_EVENT_ALARM_NAME = "Host NIC Disconnected";
    String HOST_PHYSICAL_NIC_STATUS_DOWN_EVENT_ALARM_UUID = "9a593ad138bf44138b72e0f0dd989f27";

    String HOST_CPU_AVERAGE_USED_UTILIZATION_ALARM_NAME_CN = "主机平均CPU使用率";
    String HOST_CPU_AVERAGE_USED_UTILIZATION_ALARM_NAME = "Average CPU Utilization of Hosts";
    // uuid has changed since ZSphere 4.10.3. original: "5z6gsgkc5kccpylj9ocgbd647p2700b7"
    String HOST_CPU_AVERAGE_USED_UTILIZATION_ALARM_UUID = "00d9435038505e5f90af167cfacbf611";

    String VM_CPU_AVERAGE_USED_UTILIZATION_ALARM_NAME_CN = "虚拟机平均CPU使用率";
    String VM_CPU_AVERAGE_USED_UTILIZATION_ALARM_NAME = "VM Average CPU Utilization";
    // uuid has changed since ZSphere 4.10.3. original: "uhgfoh0soh6e1qai005elfa9c6h2s2y0"
    String VM_CPU_AVERAGE_USED_UTILIZATION_ALARM_UUID = "00d78dac81854d86a056fae8d0913711";

    String VM_CPU_AVERAGE_USED_UTILIZATION_IN_GUEST_TOOLS_ALARM_NAME_CN = "虚拟机平均CPU使用率(高级监控)";
    String VM_CPU_AVERAGE_USED_UTILIZATION_IN_GUEST_TOOLS_ALARM_NAME = "VM Average CPU Utilization (Advanced Monitoring)";
    String VM_CPU_AVERAGE_USED_UTILIZATION_IN_GUEST_TOOLS_ALARM_UUID = "00dbd80dbac0494d8f351bfb640a4d11";

    String VM_MEMORY_USED_UTILIZATION_IN_GUEST_TOOLS_ALARM_NAME_CN = "虚拟机内存已用百分比(高级监控)";
    String VM_MEMORY_USED_UTILIZATION_IN_GUEST_TOOLS_ALARM_NAME = "VM Used Memory Percentage (Advanced Monitoring)";
    String VM_MEMORY_USED_UTILIZATION_IN_GUEST_TOOLS_ALARM_UUID = "00d550dd83e14bbdaf111ae087d34b11";

    String VM_MEMORY_USED_ALARM_NAME_CN = "虚拟机内存已用百分比";
    String VM_MEMORY_USED_ALARM_NAME = "VM Used Memory Percentage";
    // uuid has changed since ZSphere 4.10.3. original: "fuz2p4fa71urf4fd7cknoxsalvj60ynk"
    String VM_MEMORY_USED_ALARM_UUID = "00d781a5db9542e2b0c6ddd62e0c4811";

    String HOST_MEMORY_USED_ALARM_NAME_CN = "主机内存已用百分比";
    String HOST_MEMORY_USED_ALARM_NAME = "Host Memory Utilization";
    // uuid has changed since ZSphere 4.10.3. original: "d0b35ac37c58e358cb74e664532f1044"
    String HOST_MEMORY_USED_ALARM_UUID = "00d78ee6b5914dee9d6ac82b37207711";

    String VM_HA_START_EVENT_ALARM_NAME_CN = "虚拟机在主机HA启动";
    String VM_HA_START_EVENT_ALARM_NAME = "VM HA Started On Host";
    // uuid has changed since ZSphere 4.10.3. original: "6nz3vn2e0rdwu5hzmuetzv37ak0nj248"
    String VM_HA_START_EVENT_ALARM_UUID = "00ddf8d0949a4618a08693a2977e1211";

    String VM_STATE_IN_SHUTDOWN_EVENT_ALARM_NAME_CN = "虚拟机长时间处于in shutdown状态";
    String VM_STATE_IN_SHUTDOWN_EVENT_ALARM_NAME = "VM in Shutdown State for a Long Time";
    // uuid has changed since ZSphere 4.10.3. original: "ppfazo1y3tjvup4jfetxz36y3su98ngc"
    String VM_STATE_IN_SHUTDOWN_EVENT_ALARM_UUID = "00d6f58ce9b34437bd0ee1ba4c27c511";

    String HOST_UNKNOWN_VM_DETECTED_EVENT_ALARM_NAME_CN = "主机上发现了未受系统管控的虚拟机";
    String HOST_UNKNOWN_VM_DETECTED_EVENT_ALARM_NAME = "Unknown VM Detected On Host";
    // uuid has changed since ZSphere 4.10.3. original: "rlwalvvqyoujj3ign3o309p2zulwbhwm"
    String HOST_UNKNOWN_VM_DETECTED_EVENT_ALARM_UUID = "00d2b5ffc6d54371b9d31ef513447411";

    String MIGRATE_VM_FAILED_WITH_HOST_MAINTAIN_EVENT_ALARM_NAME_CN = "主机进入维护模式触发虚拟机迁移失败";
    String MIGRATE_VM_FAILED_WITH_HOST_MAINTAIN_EVENT_ALARM_NAME = "VM Migration Failed as Host in Maintenance Mode";
    // uuid has changed since ZSphere 4.10.3. original: "krdu1hs2314kt18ttgqndaynxchs2ufc"
    String MIGRATE_VM_FAILED_WITH_HOST_MAINTAIN_EVENT_ALARM_UUID = "00d1218c839442d69c08eb54ba2c5b11";

    String PRIMARY_STORAGE_HOST_DISCONNECTED_EVENT_ALARM_NAME_CN = "数据存储到主机连接状态检查失败";
    String PRIMARY_STORAGE_HOST_DISCONNECTED_EVENT_ALARM_NAME = "Failed to Detect Connection Between Primary Storage and Host";
    // uuid has changed since ZSphere 4.10.3. original: "8tlwqj65mus1gdolu3w61yy35pvwinhz"
    String PRIMARY_STORAGE_HOST_DISCONNECTED_EVENT_ALARM_UUID = "00dd2d1d987f4dc79e98b052126af611";

    String FAULT_MOUNT_POINT_ON_HOST_EVENT_ALARM_NAME_CN = "主机挂载路径错误";
    String FAULT_MOUNT_POINT_ON_HOST_EVENT_ALARM_NAME = "Host Mount Path Faulted";
    // uuid has changed since ZSphere 4.10.3. original: "g0eviogong06nubt1kj54z63pcka81sw"
    String FAULT_MOUNT_POINT_ON_HOST_EVENT_ALARM_UUID = "00d4a85f56394800aa9bdfbf555e0911";

    String ABNORMAL_RUNNING_VM_STATE_CHANGE_EVENT_ALARM_NAME_CN = "虚拟机所在主机异常变更";
    String ABNORMAL_RUNNING_VM_STATE_CHANGE_EVENT_ALARM_NAME = "VM Host Abnormally Changed";
    String ABNORMAL_RUNNING_VM_STATE_CHANGE_EVENT_ALARM_UUID = "eccfc93109cd4c71b56a2612d84a2773";

    String CLUSTER_QEMU_VERSION_MISMATCH_EVENT_ALARM_NAME_CN = "集群内主机QEMU版本待更新";
    String CLUSTER_QEMU_VERSION_MISMATCH_EVENT_ALARM_NAME = "QEMU Version of Hosts in Cluster Needs to be Updated";
    // uuid has changed since ZSphere 4.10.3. original: "559ca06aa8bba6990d10c255e4c9ab5b"
    String CLUSTER_QEMU_VERSION_MISMATCH_EVENT_ALARM_UUID = "00dca06aa8bb16998d10c255e4c9ab11";

    String VM_INTERNAL_IP_CHANGED_EVENT_ALARM_NAME_CN = "虚拟机内IP地址变更 (需安装性能优化工具)";
    String VM_INTERNAL_IP_CHANGED_EVENT_ALARM_NAME = "VM NIC IP Changed (GuestTools Is Required)";
    String VM_INTERNAL_IP_CHANGED_EVENT_ALARM_UUID = "98536fa94e3f4481a38331a989132b7c";

    String VM_INTERNAL_IP_DUPLICATE_EVENT_ALARM_NAME_CN = "虚拟机内IP已被占用或属于保留网段 (需安装性能优化工具)";
    String VM_INTERNAL_IP_DUPLICATE_EVENT_ALARM_NAME = "NIC IP Configured in VM has been Occupied or in the Reserved Range (GuestTools Is Required)";
    String VM_INTERNAL_IP_DUPLICATE_EVENT_ALARM_UUID = "4a3494bcdbac4eaab9e9e56e27d74a2a";

    String VM_INTERNAL_IP_RANGE_CONFLICT_EVENT_ALARM_NAME_CN = "虚拟机内IP不在端口组网络段内 (需安装性能优化工具)";
    String VM_INTERNAL_IP_RANGE_CONFLICT_EVENT_ALARM_NAME = "NIC IP Configured in VM Not in Port Group IP Range (GuestTools Is Required)";
    String VM_INTERNAL_IP_RANGE_CONFLICT_EVENT_ALARM_UUID = "520f554bd20142ff9d8be195f3bdf1a4";

    String HOST_CPU_TEMPERATURE_ALARM_NAME_CN = "主机CPU温度报警器";
    String HOST_CPU_TEMPERATURE_ALARM_NAME = "Host CPU Temperature";
    String HOST_CPU_TEMPERATURE_ALARM_UUID = "10908b6b7b8741139a5efc2b1d461a16";

    String HOST_SSD_LIFE_LEFT_ALARM_NAME_CN = "SSD剩余寿命报警器";
    String HOST_SSD_LIFE_LEFT_ALARM_NAME = "SSD Remaining Life Expectancy";
    String HOST_SSD_LIFE_LEFT_ALARM_UUID = "a3905b37d5e8477dbe0fb75a30b8f21c";

    String HOST_SSD_TEMPERATURE_ALARM_NAME_CN = "SSD温度报警器";
    String HOST_SSD_TEMPERATURE_ALARM_NAME = "SSD Temperature";
    // uuid has changed since ZSphere 4.10.3. original: "33198a88f22e4d19b5ff8ebaebb6ujm7"
    String HOST_SSD_TEMPERATURE_ALARM_UUID = "00da493006cb4668a46c09f9d4914c11";

    String HOST_PHYSICAL_MEMORY_ECC_ERROR_EVENT_ALARM_NAME_CN = "主机内存ECC告警";
    String HOST_PHYSICAL_MEMORY_ECC_ERROR_EVENT_ALARM_NAME = "Host Memory ECC Error";
    String HOST_PHYSICAL_MEMORY_ECC_ERROR_EVENT_ALARM_UUID = "258ac24eba3443dea73cbcb7758e6759";

    String HOST_PHYSICAL_MEMORY_STATUS_ABNORMAL_EVENT_ALARM_NAME_CN = "主机内存状态异常";
    String HOST_PHYSICAL_MEMORY_STATUS_ABNORMAL_EVENT_ALARM_NAME = "Host Memory Status Abnormal";
    String HOST_PHYSICAL_MEMORY_STATUS_ABNORMAL_EVENT_ALARM_UUID = "03c7c6a8ab4f492bbe06c8b03ba25f27";

    String HOST_PHYSICAL_DISK_REMOVED_EVENT_ALARM_NAME_CN = "主机硬盘拔出";
    String HOST_PHYSICAL_DISK_REMOVED_EVENT_ALARM_NAME = "Host Disk Removed";
    String HOST_PHYSICAL_DISK_REMOVED_EVENT_ALARM_UUID = "226da68a97b94b7f9f918f8ac7138873";

    String HOST_PHYSICAL_DISK_INSERTED_EVENT_ALARM_NAME_CN = "主机硬盘插入";
    String HOST_PHYSICAL_DISK_INSERTED_EVENT_ALARM_NAME = "Host Disk Plugged In";
    String HOST_PHYSICAL_DISK_INSERTED_EVENT_ALARM_UUID = "4c230269620e4e739ebc5ab2a6b0f0a4";

    String HOST_PHYSICAL_DISK_STATUS_ABNORMAL_EVENT_ALARM_NAME_CN = "主机硬盘状态异常";
    String HOST_PHYSICAL_DISK_STATUS_ABNORMAL_EVENT_ALARM_NAME = "Host Physical Disk Status Abnormal";
    String HOST_PHYSICAL_DISK_STATUS_ABNORMAL_EVENT_ALARM_UUID = "4b04f06e4ba24231ad67bd6f06093ba2";

    String HOST_PHYSICAL_CPU_STATUS_ABNORMAL_EVENT_ALARM_NAME_CN = "主机CPU状态异常";
    String HOST_PHYSICAL_CPU_STATUS_ABNORMAL_EVENT_ALARM_NAME = "Host CPU Status Abnormal";
    String HOST_PHYSICAL_CPU_STATUS_ABNORMAL_EVENT_ALARM_UUID = "8186fbbeab1d449b93e7be78d6045c7f";

    String SCHEDULER_JOB_GROUP_EXECUTED_RESULT_EVENT_ALARM_NAME_CN = "备份任务失败";
    String SCHEDULER_JOB_GROUP_EXECUTED_RESULT_EVENT_ALARM_NAME = "Backup Job Failed";
    String SCHEDULER_JOB_GROUP_EXECUTED_RESULT_EVENT_ALARM_UUID = "3123bdfa2eaf42538931113ddaec1237";

    String DISASTER_RECOVERY_STORAGE_AVAILABLE_CAPACITY_ALARM_NAME_CN = "备份存储已用容量百分比";
    String DISASTER_RECOVERY_STORAGE_AVAILABLE_CAPACITY_ALARM_NAME = "Disaster Recovery Storage Used Capacity In Percent";
    String DISASTER_RECOVERY_STORAGE_AVAILABLE_CAPACITY_ALARM_UUID = "4123f054a59a451fb1b535accff61232";

    String DISASTER_RECOVERY_STORAGE_DISCONNECT_EVENT_ALARM_NAME_CN = "备份存储未连接";
    String DISASTER_RECOVERY_STORAGE_DISCONNECT_EVENT_ALARM_NAME = "Disaster Recovery Storage Disconnected";
    String DISASTER_RECOVERY_STORAGE_DISCONNECT_EVENT_ALARM_UUID = "9123c802604e4852bd84716f66cf1233";

    String DISASTER_RECOVERY_STORAGE_CONNECTED_EVENT_ALARM_NAME_CN = "备份存储已连接";
    String DISASTER_RECOVERY_STORAGE_CONNECTED_EVENT_ALARM_NAME = "Disaster Recovery Storage Connected";
    String DISASTER_RECOVERY_STORAGE_CONNECTED_EVENT_ALARM_UUID = "51235763fed244c39b4642bef6c51239";

    String HOST_PHYSICAL_POWER_SUPPLY_STATUS_ABNORMAL_EVENT_ALARM_NAME_CN = "主机电源插槽状态异常";
    String HOST_PHYSICAL_POWER_SUPPLY_STATUS_ABNORMAL_EVENT_ALARM_NAME = "Host Power Supply Slot Status Abnormal";
    String HOST_PHYSICAL_POWER_SUPPLY_STATUS_ABNORMAL_EVENT_ALARM_UUID = "a678a66daed24779b5ef2166aaedc07b";

    String HOST_PHYSICAL_GPU_STATUS_ABNORMAL_EVENT_ALARM_NAME_CN = "主机物理GPU状态异常";
    String HOST_PHYSICAL_GPU_STATUS_ABNORMAL_EVENT_ALARM_NAME = "Host Physical Gpu Status Abnormal";
    // uuid has changed since ZSphere 4.10.3. original: "a678a66daed67879b5ef2166aaedc07b"
    String HOST_PHYSICAL_GPU_STATUS_ABNORMAL_EVENT_ALARM_UUID = "00dd520eb0dc4c828b95c3cd6b01fb11";

    String HOST_PHYSICAL_VGPU_STATUS_ABNORMAL_EVENT_ALARM_NAME_CN = "主机vGPU状态异常";
    String HOST_PHYSICAL_VGPU_STATUS_ABNORMAL_EVENT_ALARM_NAME = "Host vGPU Status Abnormal";
    // uuid has changed since ZSphere 4.10.3. original: "a678a66daed24779bbgf2166aaedc07b"
    String HOST_PHYSICAL_VGPU_STATUS_ABNORMAL_EVENT_ALARM_UUID = "00d633549c444c99be4890f096ce8e11";

    String HOST_PHYSICAL_GPU_REMOVE_EVENT_ALARM_NAME_CN = "物理GPU拔出或失联";
    String HOST_PHYSICAL_GPU_REMOVE_EVENT_ALARM_NAME = "Physical GPU Removed or Disconnected";
    // uuid has changed since ZSphere 4.10.3. original: "a678a66daed24779b5ef2zaqaaedc07b"
    String HOST_PHYSICAL_GPU_REMOVE_EVENT_ALARM_UUID = "00d0eaaeb12d40879c81cd207b83bc11";

    String HOST_GPU_TEMPERATURE_ALARM_NAME_CN = "物理GPU温度报警器";
    String HOST_GPU_TEMPERATURE_ALARM_NAME = "Physical GPU Temperature";
    // uuid has changed since ZSphere 4.10.3. original: "5z6gsgkc5kccpylj9234fd647p2700b7"
    String HOST_GPU_TEMPERATURE_ALARM_NAME_UUID = "00df1327d49e4631a21f4467aa729c11";

    String HOST_PHYSICAL_RAID_STATUS_ABNORMAL_EVENT_ALARM_NAME_CN = "主机Raid卡异常";
    String HOST_PHYSICAL_RAID_STATUS_ABNORMAL_EVENT_ALARM_NAME = "Host Physical Raid Status Abnormal";
    // uuid has changed since ZSphere 4.10.3. original: "a678a66da6093b5ef2166aaedc07b"
    String HOST_PHYSICAL_RAID_STATUS_ABNORMAL_EVENT_ALARM_UUID = "00dded12d01f464599abc47e5d9c8f11";

    String HOST_HBA_PORT_STATE_ABNORMAL_EVENT_ALARM_NAME_CN = "HBA端口状态异常";
    String HOST_HBA_PORT_STATE_ABNORMAL_EVENT_ALARM_NAME = "HBA port state abnormal event alarm";
    String HOST_HBA_PORT_STATE_ABNORMAL_EVENT_ALARM_UUID = "00db0c53c1e24b8c870ab01367478c11";

    String SHARED_BLOCK_STATE_CHANGED_EVENT_ALARM_NAME_CN = "存储共享块多路径健康状态异常";
    String SHARED_BLOCK_STATE_CHANGED_EVENT_ALARM_NAME = "PrimaryStorage Lun Multipath State Abnormal";
    String SHARED_BLOCK_STATE_CHANGED_EVENT_ALARM_UUID = "00db9a8e7f9240ffadc7f8420e905e11";

    String HOST_SHARED_BLOCK_STATE_CHANGED_EVENT_ALARM_NAME_CN = "主机共享块多路径健康状态异常";
    String HOST_SHARED_BLOCK_STATE_CHANGED_EVENT_ALARM_NAME = "Host Lun Multipath State Abnormal";
    String HOST_SHARED_BLOCK_STATE_CHANGED_EVENT_ALARM_UUID = "00db238e7f9240ffadc7f8420e905e11";

    String HOST_PROCESS_PHYSICAL_MEMORY_USAGE_NAME_CN = "主机进程物理内存使用量异常";
    String HOST_PROCESS_PHYSICAL_MEMORY_USAGE_NAME = "Host Process Physical Memory Usage Abnormal";
    String HOST_PROCESS_PHYSICAL_MEMORY_USAGE_UUID = "00db92f075384d6385303950a3cf5811";
}
