package org.zstack.sso.oauth2;

/**
 * @Author: DaoDao
 * @Date: 2022/8/23
 */
/**
 *It is used to save the data of normal authenticationand
 * prevent the exposed interface from being maliciously attacked
 */

public class AuthCache {
    //The only certain value is generated by our system to prevent other requests from accessing us
    private String state;
    private String thirdPartyRedirectUrl;
    private String scope;
    private String clientUuid;
    private String redirectUrl;
    private String zoneUuid;
    private String projectUuid;

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getThirdPartyRedirectUrl() {
        return thirdPartyRedirectUrl;
    }

    public void setThirdPartyRedirectUrl(String thirdPartyRedirectUrl) {
        this.thirdPartyRedirectUrl = thirdPartyRedirectUrl;
    }

    public String getScope() {
        return scope;
    }

    public void setScope(String scope) {
        this.scope = scope;
    }

    public String getClientUuid() {
        return clientUuid;
    }

    public void setClientUuid(String clientUuid) {
        this.clientUuid = clientUuid;
    }

    public String getRedirectUrl() {
        return redirectUrl;
    }

    public void setRedirectUrl(String redirectUrl) {
        this.redirectUrl = redirectUrl;
    }

    public String getZoneUuid() {
        return zoneUuid;
    }

    public void setZoneUuid(String zoneUuid) {
        this.zoneUuid = zoneUuid;
    }

    public String getProjectUuid() {
        return projectUuid;
    }

    public void setProjectUuid(String projectUuid) {
        this.projectUuid = projectUuid;
    }
}

