package org.zstack.header.vmscheduling;

public enum VmSchedulingRuleErrors {
    ADD_VM_ANTIAFFINITY_TO_VMGROUP_HAS_ANTIAFFINITY(3001),
    ADD_VM_ANTIAFFINITY_TO_VMGROUP_HAS_AFFINITY(3002),
    ADD_VM_AFFINITY_TO_VMGROUP_HAS_AFFINITY(3003),
    ADD_VM_AFFINITY_TO_VMGROUP_HAS_ANTIAFFINITY(3004),
    ADD_VMHOST_AFFINITY_TO_VMHOSTGROUP_HAS_AFFINITY(3005),
    ADD_VMHOST_AFFINITY_TO_VMHOSTGROUP_HAS_ANTIAFFINITY(3006),
    ADD_VMHOST_ANTIAFFINITY_TO_VMHOSTGROUP_HAS_AFFINITY(3007),
    ADD_VMHOST_AFFINITY_TO_VMGROUP_HAS_ANTIAFFINITY(3008),
    ADD_VM_ANTIAFFINITY_TO_VMHOSTGROUP_HAS_AFFINITY(3009),
    ADD_VMHOST_ANTIAFFINITY_TO_VMGROUP_HAS_ANTIAFFINITY(3010),
    ADD_VM_ANTIAFFINITY_TO_VMHOSTGROUP_HAS_ANTIAFFINITY(3011);

    private String code;

    private VmSchedulingRuleErrors(int id) {
        code = String.format("vmSchedulingRule.%s", id);
    }

    @Override
    public String toString() {
        return code;
    }
}
