<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <modules>
        <module>mevoco</module>
        <module>managements</module>
        <module>autoscaling</module>
        <module>plugin-premium</module>
        <module>zwatch</module>
        <module>sns</module>
        <module>externalservice</module>
        <module>sharedblock</module>
        <module>volumebackup</module>
        <module>cloudformation</module>
        <module>twoFactorAuthentication</module>
        <module>crypto</module>
        <module>loginControl</module>
        <module>baremetal</module>
        <module>accesskey</module>
        <module>tag2</module>
        <module>imagereplicator</module>
        <module>xdragon</module>
        <module>simulator2</module>
        <module>vpc</module>
        <module>log</module>
        <module>guesttools</module>
        <module>drs</module>
        <module>externalbackup</module>
        <module>billing</module>
        <module>network-plugin</module>
        <module>snmp</module>
        <module>iam1</module>
        <module>cbt</module>
        <module>upgrade-hack</module>
    </modules>
    <parent>
        <artifactId>zstack</artifactId>
        <groupId>org.zstack</groupId>
        <version>5.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <repositories>
        <repository>
            <id>maven-zstack-premium</id>
            <name>ZStack-Premium internal Maven Repository</name>
            <url>http://maven.nexus.zstack.io/repository/maven-zstack-premium/</url>
        </repository>
    </repositories>

    <artifactId>premium</artifactId>
    <packaging>pom</packaging>
    <dependencies>
        <dependency>
            <groupId>org.zstack</groupId>
            <artifactId>header</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.zstack</groupId>
            <artifactId>core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.zstack</groupId>
            <artifactId>utils</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.zstack</groupId>
            <artifactId>search</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.zstack</groupId>
            <artifactId>identity</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.zstack</groupId>
            <artifactId>tag</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!--<dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk16</artifactId>
        </dependency>-->
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>javax.mail</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.6</version>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>aspectj-maven-plugin</artifactId>
                <version>${aspectj.plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>       <!-- use this goal to weave all your main classes -->
                            <goal>test-compile</goal>  <!-- use this goal to weave all your test classes -->
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <source>${project.java.version}</source>
                    <target>${project.java.version}</target>
                    <complianceLevel>${project.java.version}</complianceLevel>
                    <XnoInline>true</XnoInline>
                    <aspectLibraries>
                        <aspectLibrary>
                            <groupId>org.springframework</groupId>
                            <artifactId>spring-aspects</artifactId>
                        </aspectLibrary>
                        <aspectLibrary>
                            <groupId>org.zstack</groupId>
                            <artifactId>core</artifactId>
                        </aspectLibrary>
                        <aspectLibrary>
                            <groupId>org.zstack</groupId>
                            <artifactId>header</artifactId>
                        </aspectLibrary>
                    </aspectLibraries>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
